# Generated by Django 5.1.2 on 2024-10-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_image', models.ImageField(upload_to='image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.post')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویرها',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='social_imag_created_84e743_idx')],
            },
        ),
    ]
