# Generated by Django 5.1.2 on 2024-10-25 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویرها'},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='social_imag_created_84e743_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='social_imag_created_9b48a6_idx'),
        ),
    ]
