# Generated by Django 5.1.2 on 2024-11-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_post_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('message', models.TextField(max_length=500, verbose_name='متن')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='social_tick_created_34d7f7_idx')],
            },
        ),
    ]
