# Generated by Django 5.1.2 on 2024-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_response',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='پاسخ ادمین'),
        ),
    ]
