# Generated by Django 5.1.2 on 2024-11-01 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_ticket_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
